name: Combined Workflow

on:
  push:
    branches:
      - main  # change it if your default branch is different

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 24f2002505@ds.study.iitm.ac.in
        run: echo "Hello, world!"

  cache_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-c9baa37
          restore-keys: cache-c9baa37
      - name: prime-cache-c9baa37
        run: echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
